device fujitsu {
    filter = "^fujitsu.*"
    desc   = "Fujitsu ScanSnap iX500"

    action scan {
        filter = "^scan$"
        desc   = "Scan button pressed"
        numerical-trigger {
            from-value = 1
            to-value   = 0
        }
        script = "scan.sh"
    }
}
