global {
  debug-level = 1
  user = root
  group = root
  pidfile = "/var/run/scanbd/scanbd.pid"
  timeout = 500

  environment {
    device = "SCANBD_DEVICE"
    action = "SCANBD_ACTION"
  }

  multiple-actions = true
  scriptdir = /etc/scanbd/scripts

  include(/etc/scanbd/scanner.d/*.conf)
}
