global {
  debug-level = 1
  user = root
  group = root
  pidfile = "/var/run/scanbd/scanbd.pid"
  timeout = 500

  environment {
    device = "SCANBD_DEVICE"
    action = "SCANBD_ACTION"
  }

  scriptdir = /etc/scanbd/scripts

  device fujitsu {
    filter = "^fujitsu.*"
    desc   = "Fujitsu ScanSnap iX500"

    action scan {
      filter = "^scan$"
      desc   = "Scan button pressed"
      numerical-trigger {
        from-value = 1
        to-value   = 0
      }
      script = "scan.sh"
    }
  }
}
